{{- if .Values.cluster.podMonitor.enabled }}
{{- $clusterName := .Values.cluster.clusterName | default (printf "%s-cluster" .Release.Name) }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ printf "%s-cluster-monitor" $clusterName }}
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: {{ $clusterName }}
  podMetricsEndpoints:
  - port: metrics
{{- end }}
