apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster.superuserSecret | default "superuser-secret" }}
spec:
  refreshInterval: {{ .Values.cluster.refreshPasswordInterval | default "0s" }}
  target:
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "postgres"
        password: '{{`{{ .password }}`}}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: "password-cluster-generator"
